/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import apiVideoUploader from "@api.video/strapi-uploader-plugin/strapi-admin";
import ckeditor from "../../src/plugins/strapi-plugin-ckeditor/strapi-admin";
import videoField from "@sklinet/strapi-plugin-video-field/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import fieldUuid from "strapi-auto-uuid/strapi-admin";
import responsiveImage from "strapi-plugin-responsive-image/strapi-admin";
import tagsinput from "strapi-plugin-tagsinput/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    "api-video-uploader": apiVideoUploader,
    ckeditor: ckeditor,
    "video-field": videoField,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "field-uuid": fieldUuid,
    "responsive-image": responsiveImage,
    tagsinput: tagsinput,
  },
});
